name: CI/CD Pipeline for JobOnlineAPI

on:
  push:
    branches:
      - master    # Production
      - release   # Test Site

jobs:
  test-runner:
    name: Test Runner
    runs-on: self-hosted
    steps:
      - name: Debug Environment Variables
        shell: cmd
        run: |
          echo Listing all environment variables:
          set
          echo Checking SONAR_TOKEN...
          if defined SONAR_TOKEN (echo SONAR_TOKEN is defined) else (echo SONAR_TOKEN is not defined)
        continue-on-error: true

      - name: Simple Echo
        shell: cmd
        run: |
          echo Hello, World!
          dir
        continue-on-error: true

  build-and-analyze:
    name: Build and Analyze with SonarCloud
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up .NET 8.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache SonarScanner
        id: cache-sonar-scanner
        uses: actions/cache@v4
        with:
          path: ./.sonar/scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner

      - name: Install SonarScanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        shell: powershell
        run: |
          New-Item -Path ./.sonar/scanner -ItemType Directory -Force
          dotnet tool update dotnet-sonarscanner --tool-path ./.sonar/scanner
          if ($LASTEXITCODE -ne 0) { throw "SonarScanner installation failed" }

      - name: Install Coverlet
        shell: powershell
        run: |
          dotnet tool install --global coverlet.console
          if ($LASTEXITCODE -ne 0) { throw "Coverlet installation failed" }

      - name: Validate SONAR_TOKEN
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: powershell
        run: |
          if (-not $env:SONAR_TOKEN) { throw "SONAR_TOKEN is not set or empty" }
          echo "SONAR_TOKEN is set"

      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: powershell
        run: |
          echo "Project Key: noppornnakub1_JobOnlineAPI"
          echo "Organization: noppornnakub1"
          ./.sonar/scanner/dotnet-sonarscanner begin `
            /k:"noppornnakub1_JobOnlineAPI" `
            /o:"noppornnakub1" `
            /d:sonar.token="$env:SONAR_TOKEN" `
            /d:sonar.host.url="https://sonarcloud.io" `
            /d:sonar.cs.opencover.reportsPaths="coverage.opencover.xml" `
            /d:sonar.coverage.exclusions="**Tests/**/*,**/Test/**/*" `
            /d:sonar.verbose=true
          if ($LASTEXITCODE -ne 0) { throw "SonarCloud scan start failed" }
          dotnet build JobOnlineAPI.sln --configuration Release
          if ($LASTEXITCODE -ne 0) { throw "Build failed" }
          $testProjects = Get-ChildItem -Path . -Recurse -Include *.Tests.csproj
          if ($testProjects) {
            foreach ($proj in $testProjects) {
              dotnet test $proj.FullName --no-build --configuration Release --logger "trx;LogFileName=test-results.trx" /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=coverage.opencover.xml
              if ($LASTEXITCODE -ne 0) { Write-Warning "Test project $proj failed, continuing" }
            }
          } else {
            echo "No test projects found, skipping tests"
          }
          ./.sonar/scanner/dotnet-sonarscanner end /d:sonar.token="$env:SONAR_TOKEN"
          if ($LASTEXITCODE -ne 0) { throw "SonarCloud scan completion failed" }
        continue-on-error: false

  deploy-production:
    name: Deploy to Production
    if: github.ref == 'refs/heads/master'
    runs-on: self-hosted
    needs: build-and-analyze
    env:
      ACTIONS_RUNNER_NO_SECRET_MASKING: true
    steps:
      - name: Debug Environment Variables
        shell: cmd
        run: |
          echo Listing all environment variables:
          set
          echo Checking SONAR_TOKEN...
          if defined SONAR_TOKEN (echo SONAR_TOKEN is defined) else (echo SONAR_TOKEN is not defined)
        continue-on-error: true

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check .NET SDK
        run: dotnet --list-sdks
        shell: cmd

      - name: Check IIS Status
        run: |
          net start w3svc
          iisreset /status
        shell: cmd
        continue-on-error: true

      - name: Stop IIS (Production)
        run: |
          iisreset /stop
        shell: cmd
        continue-on-error: true

      - name: Restore dependencies
        run: |
          dir
          dotnet restore JobOnlineAPI.sln
        shell: cmd

      - name: Build
        run: dotnet build JobOnlineAPI.sln --configuration Release --no-restore
        shell: cmd

      - name: Publish to Production
        run: |
          echo Publishing to C:\ONEE-JOBS\OneeJob-Backend
          dotnet publish JobOnlineAPI.csproj --configuration Release --output C:\ONEE-JOBS\OneeJob-Backend --no-build
          dir C:\ONEE-JOBS\OneeJob-Backend
        shell: cmd

      - name: Restart IIS (Production)
        run: |
          iisreset /restart
        shell: cmd

  deploy-test:
    name: Deploy to Test Site
    if: github.ref == 'refs/heads/release'
    runs-on: self-hosted
    needs: build-and-analyze
    env:
      ACTIONS_RUNNER_NO_SECRET_MASKING: true
    steps:
      - name: Debug Environment Variables
        shell: cmd
        run: |
          echo Listing all environment variables:
          set
          echo Checking SONAR_TOKEN...
          if defined SONAR_TOKEN (echo SONAR_TOKEN is defined) else (echo SONAR_TOKEN is not defined)
        continue-on-error: true

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check .NET SDK
        run: dotnet --list-sdks
        shell: cmd

      - name: Check IIS Status
        run: |
          net start w3svc
          iisreset /status
        shell: cmd
        continue-on-error: true

      - name: Stop IIS (Test Site)
        run: |
          iisreset /stop
        shell: cmd
        continue-on-error: true

      - name: Restore dependencies
        run: |
          dir
          dotnet restore JobOnlineAPI.sln
        shell: cmd

      - name: Build
        run: dotnet build JobOnlineAPI.sln --configuration Release --no-restore
        shell: cmd

      - name: Publish to Test Site
        run: |
          echo Publishing to C:\ONEE-JOBS\OneeJob-Backend-Test
          dotnet publish JobOnlineAPI.csproj --configuration Release --output C:\ONEE-JOBS\OneeJob-Backend-Test --no-build
          dir C:\ONEE-JOBS\OneeJob-Backend-Test
        shell: cmd

      - name: Restart IIS (Test Site)
        run: |
          iisreset /restart
        shell: cmd